[package]
name = "platelet-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
platelet = { path = "../platelet-rust" }
serde_json = "1.0.116"
